name: Publish Docker images

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'packages/**'
      - '.github/workflows/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      monitor: ${{ steps.filter.outputs.monitor }}
      collector: ${{ steps.filter.outputs.collector }}
      writer: ${{ steps.filter.outputs.writer }}
      kick: ${{ steps.filter.outputs.kick }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            monitor:
              - '.github/workflows/**'
              - 'apps/collector/monitor_service/**'
              - 'apps/collector/common/**'
            collector:
              - '.github/workflows/**'
              - 'apps/collector/collector_service/**'
              - 'apps/collector/common/**'
            writer:
              - '.github/workflows/**'
              - 'apps/collector/writer_service/**'
              - 'apps/collector/common/**'
            kick:
              - '.github/workflows/**'
              - 'apps/kick/**'
              - 'packages/**'

  push_to_registry:
    needs: changes
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Read version from package.json
        id: get_version
        working-directory: ./
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "Current version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push monitor service
        if: needs.changes.outputs.monitor == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/collector/monitor_service/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/huginn-monitor:${{ env.version }}
            ${{ secrets.DOCKER_USERNAME }}/huginn-monitor:latest

      - name: Build and push collector service
        if: needs.changes.outputs.collector == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/collector/collector_service/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/huginn-collector:${{ env.version }}
            ${{ secrets.DOCKER_USERNAME }}/huginn-collector:latest

      - name: Build and push writer service
        if: needs.changes.outputs.writer == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/collector/writer_service/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/huginn-writer:${{ env.version }}
            ${{ secrets.DOCKER_USERNAME }}/huginn-writer:latest

      - name: Build and push kick service
        if: needs.changes.outputs.kick == 'true'
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./apps/kick/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/huginn-kick:${{ env.version }}
            ${{ secrets.DOCKER_USERNAME }}/huginn-kick:latest
